#!/bin/python3
import subprocess as sub
from sys import argv
from sys import exit
from os import geteuid
from time import sleep

class bcolors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


print(f'''{bcolors.BLUE} {bcolors.BOLD}
        __                                                  
  _____/ /_  ____ _____  ____ ____  ____ ___  ____ ______   
 / ___/ __ \/ __ `/ __ \/ __ `/ _ \/ __ `__ \/ __ `/ ___/   
/ /__/ / / / /_/ / / / / /_/ /  __/ / / / / / /_/ / /__     
\___/_/ /_/\__,_/_/ /_/\__, /\___/_/ /_/ /_/\__,_/\___/     
                      /____/ {bcolors.GREEN}{bcolors.UNDERLINE}by abdellatif-dev
{bcolors.ENDC}
''')


if geteuid() != 0:
    exit(f"{bcolors.FAIL}{bcolors.BOLD}must run as root{bcolors.ENDC}")

else:
	if len(argv) == 3:
		option = argv[1]
		inter = argv[2]
		options = ["-e", "-a", "-A", "-p", "-r"]

		print(f"{bcolors.BLUE}{bcolors.BOLD}changing mac address {inter}{bcolors.ENDC}")
		sleep(1)

		# ifconfig <interfac_name> down
		sub.call(f"ifconfig {inter} down", shell=True)

		# macchanger

		if option in options:
			sub.call(f"macchanger {option} {inter}", shell=True)
		else:
			sub.call(f"ifconfig {inter} up", shell=True)
			exit(f"{bcolors.FAIL}{bcolors.BOLD}option {option} is not available{bcolors.ENDC}")

		sub.call(f"ifconfig {inter} up", shell=True)

		sleep(1)
		print(f"{bcolors.GREEN}{bcolors.BOLD}{inter} is ready{bcolors.ENDC}")

	elif argv[1] == "-h":
		print(f"""
{bcolors.BLUE}{bcolors.BOLD}usage:{bcolors.ENDC}{bcolors.GREEN} changemac <options> <interfac_name>{bcolors.ENDC}

{bcolors.BLUE}{bcolors.BOLD}-e{bcolors.ENDC}{bcolors.GREEN} Don't change the vendor bytes
{bcolors.BLUE}{bcolors.BOLD}-a{bcolors.ENDC}{bcolors.GREEN} Set random vendor MAC of the same kind
{bcolors.BLUE}{bcolors.BOLD}-A{bcolors.ENDC}{bcolors.GREEN} random vendor MAC of any kind
{bcolors.BLUE}{bcolors.BOLD}-p{bcolors.ENDC}{bcolors.GREEN} Reset to original, permanent hardware MAC
{bcolors.BLUE}{bcolors.BOLD}-r{bcolors.ENDC}{bcolors.GREEN} Set fully random MAC

{bcolors.BLUE}{bcolors.BOLD}-h {bcolors.ENDC}{bcolors.GREEN}for help
{bcolors.ENDC}
""")

