#!/bin/sh

txtred=$(tput setaf 1) # Red
txtgrn=$(tput setaf 2) # Green
txtylw=$(tput setaf 3) # Yellow
txtblu=$(tput setaf 4) # Blue
txtpur=$(tput setaf 5) # Purple
txtcyn=$(tput setaf 6) # Cyan
txtwht=$(tput setaf 7) # White
txtrst=$(tput sgr0) # Text reset

echo -e """${txtgrn}
 ██▓ ██▓███    ██████  █     █░▓█████ ▓█████  ██▓███
▓██▒▓██░  ██▒▒██    ▒ ▓█░ █ ░█░▓█   ▀ ▓█   ▀ ▓██░  ██▒
▒██▒▓██░ ██▓▒░ ▓██▄   ▒█░ █ ░█ ▒███   ▒███   ▓██░ ██▓▒
░██░▒██▄█▓▒ ▒  ▒   ██▒░█░ █ ░█ ▒▓█  ▄ ▒▓█  ▄ ▒██▄█▓▒ ▒
░██░▒██▒ ░  ░▒██████▒▒░░██▒██▓ ░▒████▒░▒████▒▒██▒ ░  ░
░▓  ▒▓▒░ ░  ░▒ ▒▓▒ ▒ ░░ ▓░▒ ▒  ░░ ▒░ ░░░ ▒░ ░▒▓▒░ ░  ░
 ▒ ░░▒ ░     ░ ░▒  ░ ░  ▒ ░ ░   ░ ░  ░ ░ ░  ░░▒ ░
 ▒ ░░░       ░  ░  ░    ░   ░     ░      ░   ░░ 
 ░${txtblu}\033[1mby abdellatif-dev${txtgrn}░      ░       ░  ░   ░  ░${txtrst}
"""

if [ "$1" == "" ]
then
    echo -e "${txtred}\033[1mYou forgot an IP address!${txtrst}"
    echo "Syntax: ./ipsweep 192.168.1"

else
    for ip in {1..225}; do
        ping -c 1 $1.$ip | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" &
    done
echo "" 
fi
