#!/bin/sh

txtred=$(tput setaf 1) # Red
txtrst=$(tput sgr0) # Text reset
if [ "$1" == "" ]
then
    echo -e "${txtred}\033[1mYou forgot an IP address!${txtrst}"
    echo "Syntax: ipsweep 192.168.1"

else
    for ip in {1..225}; do
        ping -c 1 $1.$ip | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" &
    done
echo "" 
fi
