#!/bin/python3

import socket
from sys import argv, exit
from datetime import datetime

# define targert


class bcolors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

print(f"""{bcolors.BLUE} {bcolors.BOLD}
                      __
    ____  ____  _____/ /__________ ___  ___
   / __ \/ __ \/ ___/ __/ ___/ __ `__ \/ _ |
  / /_/ / /_/ / /  / /_(__  ) / / / / /  __/
 / .___/\____/_/   \__/____/_/ /_/ /_/\___/
/_/ {bcolors.GREEN}{bcolors.UNDERLINE}by abdellatif-dev
{bcolors.ENDC}
""")


if len(argv) == 2 and argv[1] != "-h":
    targert = socket.gethostbyname(argv[1]) # get ip of targert
    print(f"{bcolors.BLUE}{bcolors.BOLD}targert{bcolors.ENDC}: {bcolors.BOLD}{targert}{bcolors.ENDC}")

elif len(argv) == 2 and argv[1] == "-h":
    print(f"{bcolors.BLUE}{bcolors.BOLD}usage{bcolors.ENDC}: {bcolors.GREEN}portsme {bcolors.BOLD}<ip/hostname>{bcolors.ENDC}")
else:
    print("use -h for help")
    exit(f"{bcolors.BOLD}{bcolors.FAIL}invalid target{bcolors.ENDC}")

